### ISSUE TITLE
Custom icons?

### ISSUE THREAD

**Issue by SK-Crow** [tylerdotrar/mkdocs-coverpage#1]
![image](https://github.com/tylerdotrar/mkdocs-coverpage/assets/1341176/0ca771a0-0e01-485d-a485-95479c045bfa)
# Options: "people", "gear", "image"

Is there a way to select more than just the 3 default options?  Hoping I can pull these from fontawesome.

**Comment by tylerdotrar** [comment]
A manual way for you to edit these values would be to modify the contents of `assets/home.html` with the details of your desired SVG icon.  I left it at three because the SVG icon syntax was horrendous to me, so I figured 3 options would be better than one static image.

![home.html](https://github.com/tylerdotrar/mkdocs-coverpage/assets/69973771/31d1fb08-db0e-4a32-b133-80d7755119d1)

---

I'll play around with maybe having a way to easily add and modify it from within the `mkdocs.yml` config, but until then here's a manual way for you to make your desired changes:

1. Add your custom icon details to `home.html` and title the icon something like `custom`.
```html
<!-- Custom Icon -->
{%- if config.home_button1_icon == "custom" -%}
    <svg (...details here...)>
    </svg>
{%- endif -%}
```
2. Within `mkdocs.yml`, set your icon to the new `custom` name so the site knows to use your new icon.

```yml
# Custom Homepage Button(s)
home_button1_name: Main Clicky 
home_button1_url: Folder1/                                             
home_button1_theme: md-button md-button--primary 
home_button1_icon: custom      # Options: "people", "gear", "image", "custom" (NEW!!!)
```
